# Generated by Django 4.2 on 2023-04-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=150)),
                ("review", models.CharField(max_length=500)),
                ("rating", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("semester", models.CharField(max_length=15)),
                ("year", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("industry", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your Texas A&M email", max_length=254
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=15)),
            ],
        ),
    ]
