# Generated by Django 4.2 on 2023-04-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
