# Generated by Django 4.2 on 2023-04-20 02:57

import django.core.validators
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="industry",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="salary",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="year",
            field=models.PositiveIntegerField(
                default=2023,
                validators=[
                    django.core.validators.MinValueValidator(2013),
                    post.models.max_value_current_year,
                ],
            ),
        ),
    ]
