# Generated by Django 4.0 on 2023-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_industry_alter_post_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
    ]
